### ISSUE TITLE
STOW-RS Content-Type multipart not recognised

### ISSUE THREAD

**Issue by Erwa-intra** [DICOMcloud/DICOMcloud#12]
A DICOM-WEB client send a POST request on the STOW-RS endpoint with the following Header 👍 
-		Request	{Method: POST, RequestUri: 'http://localhost:44301/stowrs', Version: 1.1, Content: System.Web.Http.WebHost.HttpControllerHandler+LazyStreamContent, Headers:
{
  Cache-Control: no-cache
  Accept: application/json
  Accept-Encoding: gzip
  Host: localhost:44301
  User-Agent: LittleBrowser
  Content-Length: 441283
  Content-Type: multipart/related; type=application/dicom; boundary=---------------------------f0d9ae2
}}

But into stowRSController.cs line 29
 if ( !Request.Content.IsMimeMultipartContent("related") )

The validation of multipartContent does not match.

With debug, the "Content" structure is 
{Content-Length: 441283
Content-Type: multipart/related; type=application/dicom; boundary=---------------------------f0d9ae2
}
And the field Content-Type cannot be extracted.

Do you encountered this problem ?

Thanks

Eric

**Comment by Zaid-Safadi** [comment]
@Erwa-intra,  Since validating the content type is performed by the .NET framework I believe it is finding a problem of how you are formatting your content type header. 

Mainly, I think you are missing " between your application/dicom type parameter:
Content-Type: multipart/related; type="application/dicom"; boundary=---------------------------f0d9ae2

However, I suggest you take a look on how the DICOMweb-js library sends this request:
Line 43: https://github.com/DICOMcloud/DICOMweb-js/blob/master/DICOMwebJS/Proxies/StowRsProxy.ts

And this method on Line 12: [getMultiPartAcceptHeader](https://github.com/DICOMcloud/DICOMweb-js/blob/master/DICOMwebJS/Proxies/MimeTypes.ts)

Please let me know if this fixes your issue.

-Zaid

**Comment by Erwa-intra** [comment]
@Zaid-Safadi 
Thanks for this highlight.
We are developping a client which follow the Dicom standard, and the 2 types of Headers are allowed.
with or without "  for the type.
Then, the implementation with .NET function IsMimeMultipartContent does not follow this standard.
Due to this implementation, we cannot use DICOMcloud as is, need some modification regarding the header management.

Eric

**Comment by Zaid-Safadi** [comment]
As far as I know only the format with " is allowed. can you point to a reference where it says both headers are?

**Comment by Erwa-intra** [comment]
@Zaid-Safadi 
Thanks for this highlight.
We are developping a client which follow the Dicom standard, and the 2 types of Headers are allowed.
with or without "  for the type.
Then, the implementation with .NET function IsMimeMultipartContent does not follow this standard.
Due to this implementation, we cannot use DICOMcloud as is, need some modification regarding the header management.

Eric

**Comment by Erwa-intra** [comment]
This is a little bit confusing, in DICOM [PS3.18](http://dicom.nema.org/medical/dicom/current/output/pdf/part18.pdf) chapter 6.6.1.1 the request is specified with ", but if we go to [RFC2387](https://tools.ietf.org/html/rfc2387) chapter 3.4 it is specified that "Note that the parameter values will usually require quoting", This sentence introduce a doubt with the word "USUALLY".
On my side we will implement with quotes. 
I close this issue.
Thanks
