### ISSUE TITLE
DICOM File upload failed

### ISSUE THREAD

**Issue by luohao110** [DICOMcloud/DICOMcloud#69]
## Expected Behavior
Success

## Actual Behavior
Failed

## Steps to Reproduce the Problem
I can succeed with Orthanc and fail with this DICOMCloud
Please check the 

- attachment

[1.2.156.14702.18.1.3.420191119081936783.zip](https://github.com/DICOMcloud/DICOMcloud/files/4038169/1.2.156.14702.18.1.3.420191119081936783.zip)

**Comment by Zaid-Safadi** [comment]
@luohao110 I don't have any problems storing this in DICOMcloud locally. What errors are you getting?

**Comment by shelbypereira** [comment]
Actually I just had this issue today with the online DICOMCloud demo.  when I check in the console I see that there is a CORS error:
Access to XMLHttpRequest at 'https://dicomcloud.azurewebsites.net/stowrs?' from origin 'http://dicomweb.azurewebsites.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Zaid-Safadi** [comment]
I don't think this is the case @shelbypereira, I just uploaded the image in the ZIP file above to the online DICOMcloud demo and it worked successfully.

**Comment by shelbypereira** [comment]
Thanks for your test and feedback,  it may be a security issue on my side because actually everything works when I run it locally.

**Comment by shelbypereira** [comment]
I understand better the issue now.  It is related to the other issue I just opened max request side exceeded Exception.  In fact althoug I was getting a CORS error, the issue has nothing to do with CORS.  it was failing for me because I was testing with an image>4MB.  

This may be the same error for luohao110 who opened the issue.

Online we canot change the file size which is ok,  I guess we don't want someone uploadingt 1GB for testing.  suggested improvement would be to have an error message appear.  Unfortunately the message that appears in the Dicomwebjs error box is always empty.
