### ISSUE TITLE
Replace database

### ISSUE THREAD

**Issue by avait1** [DICOMcloud/DICOMcloud#71]
How can I replace database or integrate with our own database to read Patients data and Dicom files through our database tables ?

**Comment by Zaid-Safadi** [comment]
@avait1 what is your database? 

If you are using MS SQL, then it will be relatively simple to support your own database, depending on the changes it could be just modifying the schema file and provide it to the code on startup:

https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud.DataAccess.Database/DatabaseSchema.xml


 Otherwise, if you are using different database (e.g Oracle, MySQL) then it will require good amount of work. 
I started a branch to support MySQL but it’s I believe 75% complete

**Comment by avait1** [comment]
@Zaid-Safadi
Hi Dear Zaid,
First, thank you for this product, it is a really beautiful thing !
we are using Clearcanvas Image Server as Pacs Server and we want to replace  Clearcanvas Image Server database to DICOMcloud DB IN DICOMcloud server for use from DICOMcloud  RESTful implementation of the DICOMweb/WADO services .

**Comment by Zaid-Safadi** [comment]
@avait1, I beleive ClearCanvas uses MS SQL so it might be easier to integrate than with other databases.
The main thing you want to look at is the XML schema file I mentioned earlier and update it to match the ClearCanvas DB. If you don't want to update DICOMcloud directly the preffered way is to pass the XML file [during initialization](https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud.Wado.WebApi/App_Start/DICOMcloudBuilder.cs#L131)

You will also see that [in this file](https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud.DataAccess.Database/Schema/StorageDBSchemaProvider.cs#L41-L53), I had to hard code some constants for main table names which you might need to update.

With that said, DICOMcloud uses an optimized way to retrieve instances and data from Disk without hitting the database which might not be compatible with ClearCanvas. If this turned out an issue for you then you will need to update the method which retrieve the location of files [in here](https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud/IO/StorageService.cs#L26-L34)
