### ISSUE TITLE
Exclude certain SOP Classes from Result

### ISSUE THREAD

**Issue by nutzlastfan** [DICOMcloud/DICOMcloud#88]
What would be the best way to exclude SOP Classes from the Resultset when querying ?

I added some lines to AddAdditionalQueryParameters:
For testing i tried whitelisting because I am not sure how to negate conditions. 

(...)
 else if (queryLevel == ObjectQueryLevelConstants.Instance)
            {
                 var condition = new SingleValueMatching();  
                condition.KeyTag = (uint)DicomTag.SOPClassUID ;
                condition.VR = DicomTag.SOPClassUID.DictionaryEntry.ValueRepresentations.First();
                var ds = new Dicom.DicomDataset();
                ds.AddOrUpdate (Dicom.DicomTag.SOPClassUID, "1.2.840.10008.5.1.4.1.1.1");
                condition.SetElement(ds.First());
                 matchingConditions.Add(condition);

This would then return only Computed Radiography Image Storage Images and I would have to this for every class I want to be returned.
What I want to do is basically block Videos and Structured report classes for the moment, ideally with blacklisting via conditions.
I hope i can get some pointers. Thanks

**Comment by Zaid-Safadi** [comment]
@nutzlastfan I think your approach might be the only way to do this right now since there is no logic to negate or exclude specific conditions.  

There was no need to implement such a capability since DICOM doesn't support (not include).

So bottom line, while might be a little tedious, you will need to add every SOP class that you allow simulating the client requesting these SOP classes.

side note, deriving from this class and overriding the method will allow you to get library updates in the future while keeping your code intact (so you don't have to merge manually). You can register your class here: https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud.Wado.WebApi/App_Start/DICOMcloudBuilder.cs#L141

**Comment by nutzlastfan** [comment]
Ok, thanks for the info.
