### ISSUE TITLE
The Storage performance is very low, how can enhance performance?

### ISSUE THREAD

**Issue by wangning08115** [DICOMcloud/DICOMcloud#98]
When use   [Route("api/studies/")] to Post many dicom files.  The StorageService.Store function performance is very low.

## Expected Behavior
When post 100 dicom files to DICOMcloud.  Can Immediately write to DICOMcloud and finished in 1-2 seconds.

## Actual Behavior
When post 100 dicom files to DICOMcloud.  Take 100 seconds , the performance is very low, i can't accept it. 

## Steps to Reproduce the Problem
When post 100 dicom files to DICOMcloud.  And total size more than 50MB.

Can you have some suggest give me?

**Comment by Zaid-Safadi** [comment]
This is probably because by default DICOMcloud generates and stored multiple representations/transfer-syntax of the DICOM file to improve steaming speed. However, if the client will only request uncompressed, you probably don't need all the rest.

Can you try commenting this and see if it improves the speed?
https://github.com/DICOMcloud/DICOMcloud/blob/development/DICOMcloud/Pacs/Commands/StoreCommand.cs#L223-L231
 
You should only leave at the min. the uncompressed format:
`            MediaTypes.Add ( new DicomMediaProperties ( MimeMediaTypes.DICOM, DicomTransferSyntax.ExplicitVRLittleEndian.UID.UID ) ) ;`

And I would also recommend leaving the JSON format. Otherwise, the server will generate every time when requested by the client.

**Comment by Zaid-Safadi** [comment]
@wangning08115 storage should be improved now with this commit  b8e24d3

**Comment by wangning08115** [comment]
This is very good way.
